/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        'xs':  ['11px', { lineHeight: '16px' }],
        'sm':  ['12px', { lineHeight: '18px' }],
        'base':['13px', { lineHeight: '20px' }],
        'md':  ['14px', { lineHeight: '22px' }],
      },
      colors: {
        'app-bg': '#faf9ff',
        'app-red': '#d83c30',
        'app-yellow': '#ffc736',
        'app-gray': '#808184',
        'rail-bg': '#1a1d23',
        'rail-icon': '#6b7280',
        'rail-icon-active': '#ffffff',
        'rail-accent': '#3b82f6',
        'nav-bg': '#f7f8fa',
        'nav-border': '#e2e4e8',
        'nav-text': '#374151',
        'nav-active-bg': '#dbeafe',
        'nav-active-text': '#1d4ed8',
        'status-bg': '#f3f4f6',
        'status-border': '#e5e7eb',
        'status-text': '#6b7280',
        'table-header': '#f9fafb',
        'table-border': '#f0f0f0',
        'row-hover': '#f5f7ff',
        'text-primary': '#111827',
        'text-secondary': '#6b7280',
        'text-muted': '#9ca3af',
      },
    },
  },
  plugins: [],
};
